version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hrapp
      - JWT_SECRET=${JWT_SECRET:-replace_me}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "start:prod"]
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: "http://localhost:3000"


volumes:
  db-data:
